version: '3'

services:
  serv00app:
    image: php:8.1.21-fpm
    working_dir: "/var/www"
    volumes:
        - ./public_html:/var/www/html
    networks:
        - internal
  mysql:
    image: "mysql:8.0.33"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # https://docs.docker.com/compose/environment-variables/set-environment-variables
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  nginx:
    restart: always
    image: nginx:latest
    ports:
        - "8080:80"
        # - "443:443"
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./public_html:/var/www/html
    depends_on:
        - serv00app
        - mysql
    networks:
        - internal

networks:
    internal:
        name: internal
